### ISSUE TITLE
cfg80211: Unknown symbol verify_pkcs7_signature (err 0)

### ISSUE THREAD

**Issue by MayHappybb** [intel/backport-iwlwifi#10]
could you help me
root@Jetson-nano:/usr/sbin# modprobe cfg80211
modprobe: ERROR: could not insert 'cfg80211': Unknown symbol in module, or unknown parameter (see dmesg)
root@Jetson-nano:/usr/sbin# dmesg
...
...
[   59.621937] cfg80211: Unknown symbol verify_pkcs7_signature (err 0)

**Comment by HaranGopal** [comment]
I have the same issue. Did you manage to resolve it?

**Comment by MayHappybb** [comment]
I found it's because my ubuntu kernal core version is too low. if you download the backport-iwlwifi:CORE60, your core version should higher than 6.0

**Comment by MayHappybb** [comment]
I found it's because my ubuntu kernel version is too low. if you download the backport-iwlwifi:CORE58, your kernel version should higher than 5.8
